### ISSUE TITLE
Faculty - affiliations

### ISSUE THREAD

**Issue by hectorcorrea** [Brown-University-Library/vivo-on-rails#32]
See if we can make sure the icons for the Faculty Affiliations can be lined up.

Code:
https://github.com/Brown-University-Library/vivo-on-rails/blob/master/app/views/faculty/_show_right_panel.html.erb#L9-L21

Example: http://localhost:3000/display/rbaier

![screen shot 2018-08-20 at 2 39 43 pm](https://user-images.githubusercontent.com/568286/44359826-f521b500-a486-11e8-9b25-35f3ce0dede0.png)

**Comment by bentbul** [comment]
These icons should be 36-px wide now (vs. 17-px wide for web link icons) -- the photo vs. public health icon may not visually align if the icon graphic has some extra white or transparent space around edges of pixel data -- will try re-saving & committing that .png without extra space at edges
